language: objective-c
osx_image: xcode8.1
rvm:
  - 2.3.0
cache:
  - bundler
  - cocoapods

before_install:
- bundle install
- bundle exec pod keys set MarvelApiKey $MARVEL_API_SECRET Marvel
- bundle exec pod keys set MarvelPrivateKey $MARVEL_API_PUBLIC Marvel
- pod repo update

script:
- fastlane test
env:
  global:
  - secure: IZJK9EhmBy8H0COFFruKu7oc8UzkS1U5AI5rm1kX29GFV8q3iSKylf+VDDRGFoc+iybCQoS7BPg265ot59mUsZ9OhDVRS5Bt8Y/dHxfho94wcoRltv1dmu9y3/msI9QtnpG1SoKKzayiidzR6a+0ZtrrNabIPrdysk1tHqako81fee+tIpX3hr7gbVuzwOfiF3847nXi7V0RZV6hzoRY8ZuPXcR8nhF/JYIS1FC98+O8Xx2SZp12wQ7EY4V5uH6RiekvhjFgElNe8gJ6drhIQwwWWapBZqW77og/VD5W/cTNhTFIkEqQQYNyUQBf//G0yGOCb3ewHbj9KEwzpqsQL10eyZo9N5OWrtTjwVxpFqL9wuqDKHTzn+fonrEANi/kDgXAXrvrqaxsXWmPiCM/grSEn7aC7vL6BtRASFzxDkN+LxGn964F3tT2L+OTUrMOx5qRMqJsfIw+HhI176DgIn2vIgoMeELhQBqMb5FzcKBSwn6fG8j5Aym6aiImsnoBPTGdnHIeTg5nFLA72DfEjGSY/SYK8EbF9D98BxDM2QdPcR4Xja7tVpvJY3YKg7T8YjH5yFg4fLTAukwB4K7LKjVD7e1SojsXqjw63oEfSP6037Uf2+lRGhU2FvcVo+u246JCpOBsNTGric0NkAUe54hmrV+Hg7N/jTM92djfh2A=
  - secure: liVAoZxn9qtFwZ3tG+UTlbap5S+/1ggqa53tXDguIL3ivnnGnn7nxI5oTuyrWQSy+PsB1mOv7tMNpHEAH/0raEHUihXry+1tetzRXQZcmBlhD/kC6epb369jigxU/SQNuLuClLLdlhbFMtaXGFOrRlNd/h4NLXnevy0ILLiRSoGQzMhW9vqVOfOiSTt2oQI6uHTXYj3y1qYVHULZunG0RGIO/gMuiI1j1UU/GoMP86a1izYJuyuKaX+ISjr870cnJdhbg6xpn++X8H+ML4yjPtdeJWbydlw/VO8907t8Z+MX+3yKcdppiFJOUx0OJTdqwq7SPep//MRCqYfx2rGL1ZKZwUOoPZtJvqpta9gjl+c9bvM422B6Ek9HcWB1uymthS9NO43W8NQPX6FqeVCiBWymIYbqebU7Ui10BPDQZl5yWUq+Um7ukS+yL9cOb5CR+ga8eT/v8OqZyxy0Co5/KS8lrXQf1XSkTSDK1pRIY0kW6gNg3brJ+eSKnNmdkAvKxQEVzy/d1IKmvQHfJisxqrsiKJUslwhClgbTiWAfiMMs1e9we7V24wqCB7RZ20lZpFWzqpwLaRkRg7im5mNXBMKox6PrK9vLdAxUrwRxT6xHy2X2fd/nfa2IgX5603Ebl5vDG+7/ZKqgWL9kzPK04Ekr35jAmbRWaBHkpWB7Ffw=
